# Generated by Django 4.1 on 2022-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_app', '0002_rename_categorie_plat_platcategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorie',
            name='photo',
            field=models.ImageField(default='', upload_to='Blog/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
